{
    'name': 'BSP Claim Monitoring',
    'version': '12.0.2.0.0',
    'development_status': "Ready for LIVE!",
    'category': 'Claim',
    'summary': "BSP Claim Monitoring",
    'author': 'didin.komarudin@gmail.com',
    'website': '',
    'license': 'AGPL-3',
    'depends': [
        'sale',
        'account',
        'operating_unit',
        'report_xlsx_helper',
        'gts_multiple_invoice_payment_currency'
    ],
    'qweb':['static/src/xml/paymentpopup_view.xml'],
    'data': [
        'security/claim_principal.xml',
        'security/ir.model.access.csv',
        'data/claim_view.xml',
        'views/width_listview.xml',
        'views/res_company_view.xml',
        'views/account_invoice_view.xml',
        'views/bsp_claim_account_payment.xml',
        'views/bsp_claim_principal_view.xml',
        'wizards/select_cl_wizard_view.xml',
        'views/bsp_pv_view.xml',
        'views/bsp_claim_lock_view.xml',
        'reports/claim_ar_monitoring_report.xml',
        'wizards/claim_ar_monitoring_wizard.xml',
        'views/bsp_claim_menu.xml',
        'views/bsp_claim_cl_view.xml',
        'views/bsp_claim_creditnote_view.xml',
        'views/bsp_claim_creditnote_alloc_view.xml',
        'views/bsp_kc_view.xml',
        'views/bsp_claim_type_view.xml',
        'views/bsp_sales_recap_view.xml',
        'views/bsp_purchase_recap_view.xml',
        'wizards/claim_confirmation_view.xml',
        'wizards/bsp_claim_print_view.xml',
        'reports/claim_monitoring_report.xml',
        'reports/report_cl_view.xml',
        'wizards/claim_monitoring_wizard.xml',
        'reports/claimcl_monitoring_report.xml',
        'wizards/claimcl_monitoring_wizard.xml',
         'reports/payment_monitoring_report.xml',
        'reports/claim_analysis.xml',
        'reports/payment_analysis.xml',


    ],
    'installable': True,
    'auto_install': False
}
